1. u1 = User.objects.create_user(username='Pupa')
u2 = User.objects.create_user(username='Lupa')
2. Author.objects.create(user=u1)
Author.objects.create(user=u2)
3. Category.objects.create(name_category='Politic')
Category.objects.create(name_category='Sport')
Category.objects.create(name_category='Stock')
Category.objects.create(name_category='Weather')
4. Post.objects.create(author=Author.objects.get(id=1), type_category='AR', name_news='Election', text_news='fact of falsification')
Post.objects.create(author=Author.objects.get(id=2), type_category='AR', name_news='Sprint', text_news='technique of running')
Post.objects.create(author=Author.objects.get(id=1), name_news='Price', text_news='The rise in price of food')
5. Post.objects.get(name_news='Election').category.add(Category.objects.get(name_category='Politic'), Category.objects.get(name_category='Weather'))
Post.objects.get(name_news='Sprint').category.add(Category.objects.get(name_category='Sport'))
Post.objects.get(name_news='Price').category.add(Category.objects.get(name_category='Stock'))
6. Comment.objects.create(post=Post.objects.get(id=1), user=Author.objects.get(id=2).user, text_comment='Nice text')
Comment.objects.create(post=Post.objects.get(id=1), user=Author.objects.get(id=2).user, text_comment='Nice title')
Comment.objects.create(post=Post.objects.get(id=2), user=Author.objects.get(id=1).user, text_comment='Bad text')
Comment.objects.create(post=Post.objects.get(id=3), user=Author.objects.get(id=2).user, text_comment='Bad title')
7. Post.objects.get(id=1).like()
Post.objects.get(id=1).like()
Post.objects.get(id=2).dislike()
Post.objects.get(id=3).like()
Comment.objects.get(id=1).like()
Comment.objects.get(id=2).dislike()
Comment.objects.get(id=3).dislike()
Comment.objects.get(id=4).like()
8. Author.objects.get(id=1).update_rating()
Author.objects.get(id=2).update_rating()
9.best = Author.objects.order_by('-rating_author')[:1]
best.values('user__username', 'rating_author')
10.bestpost = Post.objects.order_by('-rating_news')[:1]
bestpost.values('time_create_post', 'author__user__username', 'rating_news', 'name_news')
Post.objects.get(name_news=bestpost.values('name_news')).preview()
11. Post.objects.get(name_news=bestpost.values('name_news')).comment_set.all().values('time_create_comment', 'user.username', 'rating_comment', 'text_comment')

